version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
    reviewers:
      - VadVergasov
    assignees:
      - VadVergasov
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    ignore:
      - dependency-name: "idna"
